### ISSUE TITLE
Uncaught BadRequestException even though upload works

### ISSUE THREAD

**Issue by lbearl** [GoogleCloudPlatform/wordpress-plugins#42]
I'm getting the following error every time I attempt to upload a file:

`PHP Fatal error:  Uncaught exception 'Google\\Cloud\\Core\\Exception\\BadRequestException' with message 'Client error: `PUT https://www.googleapis.com/upload/storage/v1/b/xxx/o?uploadType=resumable&upload_id=AEnB2Uxxxrs2ddVLKbe_jBSlOHJHudM0DGN-Ww5_4JOMbcEWjgT1g_2D226F7B1k349bjp6PZtyHFmXepDUG-YnsRoHkKgKQoPZVw` resulted in a `400 Bad Request` response:\n<html><title>Error 400 (Bad Request)!!1</title></html>\n' in /var/www/lmydir/wp-content/plugins/gcs/vendor/google/cloud/src/Core/RequestWrapper.php:232\nStack trace:\n#0 /var/www/lmydir/wp-content/plugins/gcs/vendor/google/cloud/src/Core/RequestWrapper.php(145): Google\\Cloud\\Core\\RequestWrapper->convertToGoogleException(Object(GuzzleHttp\\Exception\\ClientException))\n#1 /var/www/mydir/wp-content/plugins/gcs/vendor/google/cloud/src/Core/Upload/StreamableUploader.php(71): Google\\Cloud\\Core\\RequestWrapper->send(Object(GuzzleHttp\\Psr7\\Request), Array)\n#2 /var/www/mydir/wp-content/plugins/gcs/vendor/google/cloud/src/Storage/WriteStream.php(66): Google\\Cloud\\Core\\ in /var/www/mydir/wp-content/plugins/gcs/vendor/google/cloud/src/Core/RequestWrapper.php on line 232, referer: https://mydir/wp-admin/post-new.php`

Note that the upload to GCP Storage is actually successful, but due to the error Wordpress doesn't record the file as having been uploaded. I am hosting wordpress using a GCP Compute Engine VM.

Please let me know if there are any other details I can provide.

**Comment by tmatsuo** [comment]
@lbearl 

Do your Compute Engine service account have the write access to the GCE bucket in question?

> Note that the upload to GCP Storage is actually successful
Do you really see the files in the GCS bucket?

I can not reproduce your problem so far. Does it happen for every image file you try to upload? If it happens only for certain images, can you send me the image file which fails? Can you share the actual operations you did when it happened? Even, is it possible to invite me (tmatsuo@google.com) to your cloud project so that I can investigate?

**Comment by lbearl** [comment]
@tmatsuo 

Thanks for the reply. I double checked that the service account that the VM is running under has write access to that bucket. I also used gsutil to upload a test file to that bucket. 

I can reliably reproduce the issue with the following steps:
1. Go to "Media > Add New" (in wordpress admin)
2. Select any file the file will appear to upload and then a message will appear saying "HTTP Error"
3. In Google Storage, the image will appear (although I just noticed that it will be 0 bytes in size)

I've added you as a project viewer to my account. Let me know if you need access to the WP admin dashboard as well. 

Thanks for your help!

**Comment by hyperpress** [comment]
Hi Luke, This reads like one of two issues I've seen before.

First, it could be caused by another plugin. Try deactivating, temporarily,
all plugins accept the Google plugin. Then check to see if upload works
correctly and without error. If it does, enable your other plugins one by
one checking the upload process until the plugin in conflict is revealed.

Second, reset Permalinks. Dashboard -> Settings​ -> Permalinks. Just save
it. Clear cache, reload, and try upload. This error can happen if
Permalinks are set to default (won't work for the uploader) or .htaccess
file in root of WordPress install contains rulesets that interfere with the
Google plugin function.

If neither fixes the problem, check Chrome browser Developer tools -
Console to see if any errors are reported. I would do this first to try and
isolate the cause.

I hope this helps. I have this plugin running on latest version of WP on a
Computer Engine instance and its working fine for me.

**Comment by lbearl** [comment]
@hyperpress  thanks for the help. I tried everything you suggested, but unfortunately that didn't seem to do it. As far as the developer tools go, they just report a 500.

@tmatsuo one thing I noticed while going through the logs is that the upload request id is the same for every upload, is that correct?

`Client error: 'PUT https://www.googleapis.com/upload/storage/v1/b/lukebearl/o?uploadType=resumable&upload_id=AEnB2Uqz40k68UJbs<snipsnip>47rj9ZuYG5ZVDp9tTd805EZHust1zECoWmY' resulted in a '400 Bad Request'`

**Comment by tmatsuo** [comment]
@lbearl Do you use the service account key for `wordpress` on the VM? Do you set environment variable `GOOGLE_APPLICATION_CREDENTIALS`?

**Comment by lbearl** [comment]
@tmatsuo I'm not using that service accout. I just removed it. Since the VM is running inside of GCP I believe the Cloud API access scopes for VM are sufficient to grant access to both SQL and Storage?

**Comment by tmatsuo** [comment]
@lbearl Still I'm not sure how to reproduce your issue. I access the VM, but it says "Error establishing a database connection" or something like that.

**Comment by lbearl** [comment]
@tmatsuo yeah... turns out I had used that service account when I configured the sql cloud proxy. I removed the proxy and white listed the web servers external IP on the SQL access control. Sorry about that. That part should be working again.

**Comment by tmatsuo** [comment]
@lbearl 
No problem. Is it possible for you to check the environment variables? Just make sure there's no `GOOGLE_APPLICATOIN_CREDENTIALS` envvar.

**Comment by lbearl** [comment]
@tmatsuo yeah, I executed `echo $GOOGLE_APPLICATION_CREDENTIALS` and it returned nothing, so that should mean it isn't set.

**Comment by tmatsuo** [comment]
@lbearl 

The shell env might different from the webserver's env. Is it possible to put a php file with `phpinfo()` and access that file via the web server and check the env vars there?

**Comment by lbearl** [comment]
@tmatsuo I created a file with `phpinfo()` and ctrl-f for "GOOGLE" returns nothing.

**Comment by tmatsuo** [comment]
@lbearl Thanks, but unfortunately I don't know why. Is it possible for me to ssh into the VM so that I can try debugging?

**Comment by lbearl** [comment]
@tmatsuo yeah, go for it. Do you need me to grant you additional privileges?

**Comment by tmatsuo** [comment]
I think the easiest way is to give me an editor access, or add this ssh key to the metadata:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC91n96GIrwGSYmdQBtVM/IUAz0GQiBUxtlmoM6qoJNBRADpT18XvOxdChf7AlIv4eRxzgCr0BuKeWa1AV/8s8cdLPVZVqUVPibz6jK6HKtlkNfTFKZls8wV5OqlOccgStGRftnF2VvshDu0g9S3Xp3OIBqx66dlzNBEjFyp6jLpDhTdIetvRFgM5l8DAr8Frr98oR66ixrUet65zMvy7y3LJpmsCAUMSP+VYbBVYGFc1dpfTrk7yWWEc3mEv6Nef/Jo9we8ABlRa1VELlaegGsG2SUY32C6cpX7VtRJJCvTRQ1Cz+irBje8d+ekrdyJdsmZrh3jbfTR/iIWpbK7BWA1gL9rXGEO/suz3Ay+aV4NFGl6PApG8Lq/0o2FCY9j0SPqSPs1RZg7J5iDJI74uP86NwmGfi0PyBMJ2YRatsfZpVPDjxzqaU/Y+9nQoyUk03B5DgL11i9Vk/c1Q+wK5SAxHO7g6yDvxEg6rXW+cPYL1J+nbAQOFUSradgMlpEASpcuDowgkpy14SzIuwwfP1F3hna5HJnmtS2JA0Fw+LWyUOGpglvvShZ4nugWDsIqa0K0e4h5DuXrrLLtAXnTg5lTzhWoIqiFXBM4Z1BAd8CsGaFsL59X0ScAB81iy7fk7YtNpAgu0c+KYhFthXGy1c4ojxw5Lwd1bzzo3HPXn4rEQ== tmatsuo@t-glaptop
```

**Comment by lbearl** [comment]
I've promoted you to have project editor permissions.

**Comment by tmatsuo** [comment]
Thanks. I think I started understand what's happening. My hypothesis now is it may need full storage permission for the resumable upload.

**Comment by lbearl** [comment]
That sounds plausible. I'll change the VM's API access scopes and report back. Thanks for your help tonight.

**Comment by tmatsuo** [comment]
Good news is that I reproduced the same issue with my own compute instance :)

Bad news is that I still don't know why. My instance has Full cloud access, but it still fails. I assume it's not a permission related.

https://cloud.google.com/storage/docs/best-practices

> If you use Google Compute Engine instances with processes that POST to Cloud Storage to initiate a resumable upload, then you should use Compute Engine instances in the same locations as your Cloud Storage buckets. You can then use a geo IP service to pick the Compute Engine region to which you route customer requests, which will help keep traffic localized to a geo-region.

Maybe it's related, but we're all using multi regional storage bucket in US and GCE instance in us, so I'm at a loss. I'll investigate further tomorrow.

**Comment by tmatsuo** [comment]
Filed a bug on the google-cloud-php repo: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/447

**Comment by tmatsuo** [comment]
@lbearl 

Hi, I think we found a workaround. Can you enable `curl` extension and try it again? If you're just using debian package, you can just do `sudo apt-get update && sudo apt-get install -y php5-curl`.

**Comment by hyperpress** [comment]
That makes sense as we've not been able to reproduce this on our Dev
instance on FACE with curl enabled, but just disabled curl on one instance
and it fails with same error.

**Comment by tmatsuo** [comment]
@hyperpress Thanks for the additional data point!

Ideally the underlining library should just work without curl, so we'll keep investigating why, but in general installing `curl` is easy and most of the users won't have a problem doing so.

**Comment by hyperpress** [comment]
Welcome. Yes, most hosting providers including ours enables curl extension
by default, so the interim workaround should be trivial. Thanks again for
the plugin.

On Apr 12, 2017 3:51 PM, "Takashi Matsuo" <notifications@github.com> wrote:

@hyperpress <https://github.com/hyperpress> Thanks for the additional data
point!

Ideally the underlining library should just work without curl, so we'll
keep investigating why, but in general installing curl is easy and most of
the users won't have a problem doing so.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/GoogleCloudPlatform/wordpress-plugins/issues/42#issuecomment-293703798>,
or mute the thread

**Comment by lbearl** [comment]
@tmatsuo thanks for all your help! I've installed curl and restarted apache and now it is working. @hyperpress  thanks for all your help as well.
